In [1]:
import numpy as np

import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
a = np.array([1,2])
b = np.array([2,1])

a*b

array([2, 2])

In [3]:
np.dot(a,b)

4

In [4]:
np.sum(a*b)

4

In [6]:
a.dot(b)

4

In [7]:
b.dot(a)

4

In [9]:
np.sqrt(a**2 + b**2)

array([2.23606798, 2.23606798])

In [10]:
np.linalg.norm(a)

2.23606797749979

In [13]:
cosangle = a.dot(b)/(np.linalg.norm(a)*np.linalg.norm(b))
cosangle

0.7999999999999998

In [15]:
angle = np.arccos(cosangle)
angle

0.6435011087932847

In [18]:
np.sqrt(5)

2.23606797749979

### Matrices

Matrices can be thought of as list of lists

Officially in general don't use Matrix use Arrays

In [20]:
M = np.array([[1,2], [3, 4]])
L = [[1,2], [3, 4]]

In [21]:
L[0]

[1, 2]

In [22]:
L[0][0]

1

In [24]:
M[0][0]

1

In [25]:
M[0,0]

1

In [26]:
M2 = np.matrix([[1,2], [3, 4]])
M2

matrix([[1, 2],
        [3, 4]])

In [27]:
A = np.array(M2)
A

array([[1, 2],
       [3, 4]])

In [28]:
A.T

array([[1, 3],
       [2, 4]])

### Create Arrays

In [30]:
Z = np.zeros(10)
Z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [34]:
Z = np.zeros((10,10))
Z

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [35]:
O = np.ones((10,10))
O

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [37]:
R = np.random.random((10,10))
R

array([[0.67554928, 0.29590523, 0.71166501, 0.96073991, 0.47558743,
        0.89528611, 0.86933487, 0.44913241, 0.29301686, 0.85039654],
       [0.00106846, 0.76727802, 0.74483478, 0.17822712, 0.84289295,
        0.22303027, 0.58271225, 0.11330298, 0.74187192, 0.26971475],
       [0.75393467, 0.45705206, 0.3527923 , 0.80758154, 0.58982916,
        0.833147  , 0.24211981, 0.68398161, 0.65417637, 0.61457909],
       [0.66872056, 0.59389067, 0.14624363, 0.1978268 , 0.10815851,
        0.06397329, 0.26196275, 0.53230731, 0.24313906, 0.09382022],
       [0.59936681, 0.2793293 , 0.25634992, 0.87282223, 0.58709105,
        0.36884081, 0.11497478, 0.20001169, 0.71229411, 0.45452594],
       [0.93799582, 0.7420862 , 0.7080089 , 0.41874828, 0.71438861,
        0.79295638, 0.74831723, 0.69394719, 0.40454762, 0.47391032],
       [0.39798439, 0.16774385, 0.24696893, 0.82880419, 0.29463829,
        0.87256735, 0.14328496, 0.81294097, 0.65140371, 0.65470748],
       [0.18278564, 0.47066366, 0.4927643

In [39]:
G = np.random.randn(10,10)
G

array([[ 1.46216617, -1.43812242, -0.83511201,  1.40422063, -0.70772   ,
         0.22876295, -0.37081061,  0.53850432,  0.35527006, -1.45679522],
       [-0.40346378,  0.53009308, -0.40907343, -1.75607886,  0.92129236,
         0.21733486,  0.29654333, -0.84197124,  0.45432843,  0.05211637],
       [ 0.19264307,  0.02676147, -1.44438303, -0.15685842, -1.47389881,
         0.10023238,  0.65245082,  0.36187083, -0.82048444,  0.6692589 ],
       [-2.35067384,  1.30052355,  1.20010075, -0.06368219,  1.35478844,
         0.6693073 ,  0.22208192, -0.37190357,  0.94324095,  1.24867066],
       [ 0.03914774, -0.26673078,  1.50551235, -0.60114924,  2.02624678,
        -0.11794703, -1.58942519, -0.9084871 , -0.36157304, -0.23850903],
       [-0.18730406,  0.08261091,  1.85742543,  1.77254369,  0.23362264,
         0.22947903, -1.41141202, -0.87651812,  0.48006735, -0.01852513],
       [-0.83085315, -0.25708669, -0.50977657, -0.1142754 , -1.50248076,
         0.31981631, -2.62173602,  0.27037619

### Matrix Multiplication (Dot Product)

This:

$$a\cdot b$$

Not 

$$a x b$$


### Matrix Operations

In [46]:
# Inverse
A = np.array([[1,2], [3,4]])
A

array([[1, 2],
       [3, 4]])

In [47]:
Ainv = np.linalg.inv(A)
Ainv

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [42]:
Ainv.dot(A)

array([[1.00000000e+00, 0.00000000e+00],
       [1.11022302e-16, 1.00000000e+00]])

In [43]:
np.linalg.det(A)

-2.0000000000000004

In [44]:
np.diag(A)

array([1, 4])

In [48]:
np.diag([1,2])

array([[1, 0],
       [0, 2]])

In [49]:
a = np.array([1,2])
b = np.array([3,4])
np.outer(a,b)

array([[3, 4],
       [6, 8]])

In [50]:
np.inner(a,b)

11

In [51]:
a.dot(b)

11

In [52]:
np.diag(A).sum()

5

In [53]:
np.trace(A)

5

In [56]:
X = np.random.randn(100,3)

In [63]:
# Have to transpose the matrix first when finding the covariance
cov = np.cov(X.T)
cov
print(cov.shape)

(3, 3)


In [64]:
# returns the eignvalues & eigenvectors of a Hermitian matrix respectively
np.linalg.eigh(cov)

(array([0.74846969, 0.90614874, 0.97548407]),
 array([[-0.38981452, -0.79235017,  0.46928228],
        [ 0.46629929,  0.26960344,  0.84254315],
        [ 0.79410932, -0.54726154, -0.26437698]]))

In [66]:
# returns the eignvalues & eigenvectors of a Symmetric matrix respectively
np.linalg.eig(cov)

(array([0.74846969, 0.90614874, 0.97548407]),
 array([[ 0.38981452, -0.79235017, -0.46928228],
        [-0.46629929,  0.26960344, -0.84254315],
        [-0.79410932, -0.54726154,  0.26437698]]))

### Solving a Linear System

$$Ax=b$$
$$A^{-1}Ax=x=A^{-1}b$$

In [67]:
A

array([[1, 2],
       [3, 4]])

In [70]:
b = np.array([1,2])
b

array([1, 2])

In [71]:
x = np.linalg.inv(A).dot(b)
x

array([0. , 0.5])

In [72]:
# More optimal way in numpy
np.linalg.solve(A, b)

array([0. , 0.5])

In [74]:
# 1st equation: X1 + X2 = 2200
# 2nd equation: 1.5*X1 + 4*X2 = 5050
A = np.array([[1, 1], [1.5, 4]])
b = np.array([2200, 5050])

np.linalg.solve(A, b)

array([1500.,  700.])

In [75]:
# Double Check
1500*1.5 + 700*4

5050.0